name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            whoami
            pwd
            echo "Testing SSH connection"
            mkdir test
            cd test
            git clone git@github.com:StigAkl/ms-routes.git
            echo 'Success!'
