name: Build and Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t myapp .
          docker save myapp > myapp.tar

      - name: Transfer Docker image to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "myapp.tar"
          target: "/tmp"

      - name: Load and Run Docker image on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker load < /tmp/myapp.tar
            docker stop myapp || true
            docker rm myapp || true
            docker run --name myapp -d -p 5173:5173 myapp
